name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache de Dependências do Node.js
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Instalar Dependências
        run: npm ci

      - name: Iniciar Servidor de Desenvolvimento
        run: npm run dev &

      - name: Esperar o Servidor Estar Pronto
        run: npx wait-on http://localhost:5173

      - name: Executar Testes Cypress
        run: npm run test:e2e